name: check
on:
  push:
    branches:
      - master
      - heartwood
  pull_request:
    branches:
      - master
      - heartwood

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run check
